version: '3'
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - ENABLE_OAUTH_SIGNUP=true
      - ENABLE_LOGIN_FORM=false
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true


      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OPENID_PROVIDER_URL=https://auth.ghost4.duckdns.org/.well-known/openid-configuration
      - OAUTH_PROVIDER_NAME=Authelia
      
      - ENABLE_OAUTH_ROLE_MANAGEMENT=true
      - OAUTH_ALLOWED_ROLES=users
      - OAUTH_ADMIN_ROLES=admins

    volumes:
      - ./data/open_webui/:/app/backend/data
    networks:
      - proxy

networks:
  proxy:
    external: true



# The allowed redirect URI should include <open-webui>/oauth/oidc/callback.

# claims, email (required), name, picture


