version: "3.8"

services:
  psitransfer:
    container_name: psitransfer
    image: psitrax/psitransfer
    restart: always    
    ports:
      - "3000:3000"
    environment:
      - PSITRANSFER_ADMIN_PASS=${PSITRANSFER_ADMIN_PASS}
      # - PSITRANSFER_UPLOAD_PASS=${PSITRANSFER_ADMIN_PASS}
      - PSITRANSFER_MAXFILESIZE=2147483648
    volumes:
      - "./data:/data"
      # - "./data/config.js:/app/config.js"
    networks:
      - proxy

networks:
  proxy:
    external: true
